export const HOLLOW_IRIS_TEXT = `She woke on a floor she didn't know. The ceiling was old plaster, water-stained in the shape of a coastline. The room smelled of damp stone and something mineral and sweet that she had no category for. Light through the high window was grey and morning. She had been lying on her side with her arm under her head, and when she lifted it her arm was numb. She stood. The numbness resolved. She walked to the door. The door was unlocked. She walked out of it into a corridor, and the corridor into a street, and the street was the city. She had no plan and no origin and no word for either of these facts, but she had the city, and she walked into it the way she would come to understand she did everything in those first hours. The Outer Ring of Myrhold was already in full operation. Market stalls uncovering their displays, vendors calling to each other across the lanes. The transit ring ran overhead on its own power circuit, its mechanical bell striking the quarter-hours with the precision of something that had always been mechanical and never been anything else. The lamp-posts were at noon-rate, their hum a steady middle-pitch she would come to use as a reference point. In a civilization shaped by an institution most people trust without understanding, a young woman named Nora Hale leaves the capital planet Kairon to study on Ananke, the administrative world where the system that governs human continuity is centered. There, she meets Iris Valen, a woman whose warmth defies the engineered coolness of everything around her. Her hand was warm. The wall remembered. Nothing else did. She hated this. She was magnificent at it. The hum at zero point eight seconds. The first time is the crack. She held the language honest. The coat before words. Temperature differential becoming only two temperatures. Take me home. She catalogued the deliberate not-looking as a behavior and tried to replicate it, imperfectly, she kept looking, not knowing yet what not-looking was for.`;

export const ROOT_CROWN_TEXT = `The spare room had been empty since the spring, when Bareth's sister had stayed a week and gone south again. Mira had aired it after, left the window open for a morning, the cot's bedding shaken and refolded, and since then left it as it was, which was tidy and sufficient and a room that served its purpose by holding itself ready. Ifian asked to use the table in the third week of autumn. Not to sleep in, he had the room above the flour-shed, the corner room where you could hear the wood settling through the floor in cold nights, and he had been in it since his arrival without giving any visible sign of wanting to leave. What he wanted was a place to write that could be left between sessions without needing to be cleared. It was the kind of request that assumed the household had space to spare, and it did. Mira said of course. Lyssa said of course and carried the traveling things that had accumulated on the table during the summer out to the hall shelf, where they belonged. Ifian thanked them both in the brief way he thanked things. That evening carried his writing box from the traveling pack to the room and arranged it on the table: the box itself, cherrywood, worn smooth from twenty years of travel, the latch polished to the particular sheen of brass handled daily. Inside it the parchment he carried wherever he went and the ink he made from scriptorium-supplied minerals, a ceramic vessel sealed with wax. Filed under unknown, kept. He did not ask the next question. Her hands moved before the calculation finished. You're letting me go. Yes. All right. Does it know it's us. Asking. Two women separated by centuries touch the same buried thing. Neither knows what the other is. The connection between them will not be named for a hundred and seventy-eight chapters.`;

export function getTextWallLines(): string[] {
  const combined = HOLLOW_IRIS_TEXT + " " + ROOT_CROWN_TEXT;
  const words = combined.split(/\s+/);
  const lines: string[] = [];
  const wordsPerLine = 12;

  for (let i = 0; i < words.length; i += wordsPerLine) {
    lines.push(words.slice(i, i + wordsPerLine).join(" "));
  }

  while (lines.length < 40) {
    lines.push(...lines.slice(0, 40 - lines.length));
  }

  return lines;
}
